### ISSUE TITLE
Implementing Shodan reconnaissance in OWASP-Nettacker

### ISSUE THREAD

**Issue by aman566** [zdresearch/OWASP-Nettacker#204]
There is no way that current version of nettacker can search on shodan and do information gathering. I will add this feature such that shodan search will also get implemented in nettacker.

**Comment by securestep9** [comment]
Hi @aman566 - Shodan is not free and opensource. Feel free to add the shodan module via pull request - please allow Nettacker users to use their own Shodan API key

**Comment by aman566** [comment]
Please assign this task to me. Currently I am understanding the codebase of Nettacker. After that I will implement a shodan module in which user will be giving his api key and according to it the results will vary.

**Comment by aman566** [comment]
can you please assign this task to me? I am on it and will soon update you with the code.

**Comment by SriHarshaGajavalli** [comment]
Assigned you, Aman. Send a PR once you're done

**Comment by iDuronto** [comment]
Hey @SriHarshaGajavalli, @securestep9,
Please assign an issue to someone only after they have opened a PR on the issue. There are other people like me willing to work on this issue. But since this is assigned to someone else, I can't work on this now, or can I? Please help.

I'm waiting upon you guys to start contributing. :)

Regards

**Comment by aman566** [comment]
I was working on SSL implementation. Now it's completed. I will start working on this problem. Due to corona issues in our college, I was not able to work. Once the director is confortable in giving us holidays I will surely update the repo.
